"""initial

Revision ID: 4fcbc8dd1a8b
Revises: 
Create Date: 2026-07-29 20:48:57.714729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcbc8dd1a8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('external_requester_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_requester_id'),
    sa.UniqueConstraint('requester_email')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('external_ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'SOLVED', 'NEW', 'PENDING', 'HOLD', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='ticket_priority'), nullable=False),
    sa.Column('assignee_external_id', sa.BigInteger(), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('source_created_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ticket_id')
    )
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_table('satisfaction_ratings',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Enum('GOOD', 'BAD', 'UNOFFERED', 'OFFERED', name='satisfaction_score'), nullable=False),
    sa.Column('offered_at', sa.DateTime(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satisfaction_ratings_ticket_id'), 'satisfaction_ratings', ['ticket_id'], unique=True)
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'tag_id', name='uq_ticket_tags_ticket_id_tag_id')
    )
    op.create_index(op.f('ix_ticket_tags_tag_id'), 'ticket_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_ticket_tags_ticket_id'), 'ticket_tags', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_tags_ticket_id'), table_name='ticket_tags')
    op.drop_index(op.f('ix_ticket_tags_tag_id'), table_name='ticket_tags')
    op.drop_table('ticket_tags')
    op.drop_index(op.f('ix_satisfaction_ratings_ticket_id'), table_name='satisfaction_ratings')
    op.drop_table('satisfaction_ratings')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('customers')
    # ### end Alembic commands ###
